{
 "title": "Application",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество обработанных ботом страниц",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "crawler_pages_parsed" }
   ]
  },
  {
   "title": "Количество обработанных запросов веб-интерфейсом приложения",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "web_pages_served" }
   ]
  },
  {
   "title": "90-й процентиль времени генерации веб-страниц, учитывая время обработки запросов",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(web_page_gen_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "90-й процентиль  затраченного времени на обработку ботом содержимого веб-страниц",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(crawler_page_parse_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "90-й процентиль затраченного времени на подключение бота к веб-сайтам и загрузки веб-страниц",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(crawler_site_connection_time_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}