global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#devops'
